receivers:
  otlp/notls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ${env:OTEL_COLLECTOR}
    headers:
      Authorization: "Bearer ${env:API_TOKEN}"
processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [debug]
